### PR TITLE
Adds weapon enum instead of string

### PR DESCRIPTION
**Pull request by werogg**
- Changed weapon name from String to Weapon enum
- Keep weapon#getName() as Weapon getter
- Added tests

### CODE REVIEW

**Comment by koczadly** [comment]
Thanks so much mate, I really appreciate your efforts. I was planning on doing this back when I made the library, but I couldn't find a definitive list of all the weapon names at the time. Appears to be working great, so I've merged it. Thanks :)

**Comment by werogg** [comment]
> Thanks so much mate, I really appreciate your efforts. I was planning on doing this back when I made the library, but I couldn't find a definitive list of all the weapon names at the time. Appears to be working great, so I've merged it. Thanks :)

You can find them here: https://developer.valvesoftware.com/wiki/List_of_Counter-Strike:_Global_Offensive_Entities

**Comment by koczadly** [comment]
There we go, I knew there had to be a list somewhere. I was just too lazy to equip each weapon and then check the response to find the values 😂.

**Comment by koczadly** [comment]
Just realised why I didn't immediately do this — the new danger zone items aren't all listed, and there's a few weird weapons (weapon_knife_ct, etc). I'll see what I can find and add these to the enum you created.

**Comment by werogg** [comment]
That's true, just seen that there are all this missing:

**Comment by koczadly** [comment]
I'm working on it, no worries mate. You've given me motivation to finally work on something while I'm locked in the house and end the boredom.

Seems that `weapon_knife` refers to the CT knife, and `weapon_knife_t` refers to the terrorist knife. Also found a few missing `WeaponType` variations that I didn't originally include, so I'm also gonna add them.

Cheers for all the help mate, it's much appreciated :)

**Comment by werogg** [comment]
Hah, really got into this project while looking for apis to use in my next csgo android app, and definitely decided to use yours, as I've seen that you are really maintaining this repo.

**Comment by koczadly** [comment]
Oh awesome, what kinda app are you making?

**Comment by werogg** [comment]
It's a live match info app while you are pooping or away from keyboard ^^. I try to keep all csgo's hud info on the phone, adding extra sats info and give some eco round combinations to keep the economy witohut thinking too much.

**Comment by koczadly** [comment]
That sounds like an awesome idea bro, hope it all works out :)

**Pull request merged**
